require("core.options")
require("core.keymaps")
require("core.installations").setup()
require("lazy").setup(require("plugins"))
require("plugins.colorscheme").setup()
require("core.activations").activate()
